### ISSUE TITLE
Python: "ValueError: Missing `tool.hatch.version` configuration" when trying to install

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#34]
@Finnventor, I get `ValueError: Missing `tool.hatch.version` configuration` when I try to install the latest Python version. Do you know how to resolve this?  (I'm puzzled, because it does not occur on GitHub Actions, which basically does the same commands).

```sh
$ pip install .
Defaulting to user installation because normal site-packages is not writeable
Processing /home/henrik/repositories/port4me/python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/henrik/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/henrik/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/henrik/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/henrik/pip-build-env-eopumzls/overlay/local/lib/python3.10/dist-packages/hatchling/build.py", line 56, in build_wheel
          return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
        File "/tmp/henrik/pip-build-env-eopumzls/overlay/local/lib/python3.10/dist-packages/hatchling/builders/plugin/interface.py", line 93, in build
          self.metadata.validate_fields()
        File "/tmp/henrik/pip-build-env-eopumzls/overlay/local/lib/python3.10/dist-packages/hatchling/metadata/core.py", line 243, in validate_fields
          _ = self.version
        File "/tmp/henrik/pip-build-env-eopumzls/overlay/local/lib/python3.10/dist-packages/hatchling/metadata/core.py", line 128, in version
          self._version = self._get_version()
        File "/tmp/henrik/pip-build-env-eopumzls/overlay/local/lib/python3.10/dist-packages/hatchling/metadata/core.py", line 226, in _get_version
          version = self.hatch.version.cached
        File "/tmp/henrik/pip-build-env-eopumzls/overlay/local/lib/python3.10/dist-packages/hatchling/metadata/core.py", line 1384, in version
          raise ValueError(message)
      ValueError: Missing `tool.hatch.version` configuration
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

# Session information

```sh
$ python --version
Python 3.10.6

$ hatch --version
Hatch, version 1.7.0

$ python -m pip install --upgrade pip
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pip in /home/henrik/.local/lib/python3.10/site-packages (23.1.2)

$ pip install flake8 pytest
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: flake8 in /home/henrik/.local/lib/python3.10/site-packages (6.0.0)
Requirement already satisfied: pytest in /home/henrik/.local/lib/python3.10/site-packages (7.3.2)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in /home/henrik/.local/lib/python3.10/site-packages (from flake8) (0.7.0)
Requirement already satisfied: pycodestyle<2.11.0,>=2.10.0 in /home/henrik/.local/lib/python3.10/site-packages (from flake8) (2.10.0)
Requirement already satisfied: pyflakes<3.1.0,>=3.0.0 in /home/henrik/.local/lib/python3.10/site-packages (from flake8) (3.0.1)
Requirement already satisfied: iniconfig in /home/henrik/.local/lib/python3.10/site-packages (from pytest) (2.0.0)
Requirement already satisfied: packaging in /usr/lib/python3/dist-packages (from pytest) (21.3)
Requirement already satisfied: pluggy<2.0,>=0.12 in /home/henrik/.local/lib/python3.10/site-packages (from pytest) (1.0.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc8 in /home/henrik/.local/lib/python3.10/site-packages (from pytest) (1.1.1)
Requirement already satisfied: tomli>=1.0.0 in /home/henrik/.local/lib/python3.10/site-packages (from pytest) (2.0.1)
```

**Comment by HenrikBengtsson** [comment]
I think I figured it out, cf. commit 9a11b31f.
