### ISSUE TITLE
Bash: port4me thinks an occupied port is available

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#48]
```sh
# R
$ Rscript -e port4me::port4me --test=37216 && echo "avail" || echo "bound"
bound

# Python
$ python3 -m port4me --test=37216 && echo "avail" || echo "bound"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/wynton/home/cbi/hb/.local/lib/python3.11/site-packages/port4me/__main__.py", line 25, in <module>
    if port4me(**args):
       ^^^^^^^^^^^^^^^
  File "/wynton/home/cbi/hb/.local/lib/python3.11/site-packages/port4me/__init__.py", line 167, in port4me
    return is_port_free(test)
           ^^^^^^^^^^^^^^^^^^
  File "/wynton/home/cbi/hb/.local/lib/python3.11/site-packages/port4me/__init__.py", line 33, in is_port_free
    s.bind(("", port))
OSError: [Errno 98] Address already in use
bound

# Bash
$ port4me --test=37216 && echo "avail" || echo "bound"
avail

$ netstat | grep 37216
tcp        0      0 dev1.wynton.ucsf.:37216 bmd5.wynton.ucsf.e:8105 ESTABLISHED

$ ss | grep 37216
tcp   ESTAB      0      0                                                               172.26.44.131:37216          172.26.36.39:8105
```

**Comment by HenrikBengtsson** [comment]
The Bash implementation of `port4me` uses:

```sh
$ port=37216

$ nc -z 127.0.0.1 "${port}"; echo $?
1

$ ss -H -l -n src ":${port}" | grep -q -E ":${port}\b"; echo $?
1

$ netstat -n -l -t | grep -q -E "^tcp\b[^:]+:${port}\b"; echo $?
1
```

If these have exit code 0, then the port is considered occupied.

These all fail, despite having:

```sh
$ ss | grep 37216
tcp   ESTAB      0      0                                                                   172.26.44.131:37216          172.26.36.39:8105

$ netstat | grep 37216
tcp        0      0 dev1.wynton.ucsf.:37216 bmd5.wynton.ucsf.e:8105 ESTABLISHED
```

For the record, we also have:

```sh
$ ss -H -l -n src ":${port}"; echo $?
0
```

**Comment by HenrikBengtsson** [comment]
A quick thought/idea: Use `netstat` to find established ports and look at how our different port4me implementations work on each of them and see if there are more things to learn.  Gist:

```sh
mapfile -t ports < <(netstat | grep ESTABLISHED | awk '{ print $4 }' | sed 's/.*://' | grep -E "^[[:digit:]]+$" | sort -u | sort -h) 
echo "Number of ports: ${#ports[@]}"
## Number of ports: 813
for port in "${ports[@]}"; do printf "%d: %s\n" "${port}" "$(port4me --test="${port}" && echo "free" || echo "busy")"; done
```

**Comment by HenrikBengtsson** [comment]
For `nc`, we need to use:

```sh
$ timeout 0.1 nc -l "${port}"
Ncat: bind to 0.0.0.0:33076: Address already in use. QUITTING.
$ echo $?
2
```

If the port is available, we'll get:

```sh
$ timeout 0.1 nc -l "${port}"
Ncat: bind to 0.0.0.0:33076: Address already in use. QUITTING.
$ echo $?
124
```

**Comment by HenrikBengtsson** [comment]
I think I've fixed this. Bugs in the `nc` and `ss` approaches. `netstat` worked, but `nc` was the default, then `ss`.

The remaining task is to add a better unit test for this.  Maybe something like:

1. Find a free TCP port.
2. Bind it for 5 seconds in background process.
3. Verify that `port4me` detects it as non-available.

Prototype:

```sh
port=$(port4me --tool="port4me-tests")
timeout 5 nc -l "${port}" &  ## bind in the background
pid=$!

ok=true
if port4me --test="${port}"; then
   ok = false
fi

# Terminate background process
kill -SIGTERM "${pid}"
wait "${pid}"

if ! ok; then
    2>&1 "echo "ERROR: port4me failed to detect port as non-available"
    exit 1
fi
```

**Comment by HenrikBengtsson** [comment]
Hmm... the above unit test works on Rocky 8 Linux, but not on Ubuntu 22.04 / GitHub Actions;

```sh
 not ok 21 port4me --test=<BUSY_PORT> works
# (from function `fail' in file /home/runner/work/port4me/port4me/bats-support-0.3.0/src/error.bash, line 40,
#  in test file port4me.bats, line 144)
#   `${ok} || fail "ERROR: port4me failed to detect port as non-available"' failed
# /usr/bin/nc
# ERROR: port4me failed to detect port as non-available
```

Using `nc -l <port>` for testing does not work here; it happily binds to the same port again;

```sh
$ port=26142
$ nc -l "${port}" &
$ timeout 1.0 nc -l "${port}"
$ echo $?
124
```

**Comment by HenrikBengtsson** [comment]
Oh, `nc` is not the same on Rocky 8 and Ubuntu 22.04;

```sh
{rocky8}$ command -v nc
/usr/bin/nc
{rocky8}$ realpath /usr/bin/nc
/usr/bin/ncat
{rocky8}$ nc --version
Ncat: Version 7.70 ( https://nmap.org/ncat )
```

```sh
{ubuntu22.04}$ command -v nc
/usr/bin/nc
{ubuntu22.04}$ realpath /usr/bin/nc
/usr/bin/nc.openbsd
{ubuntu22.04}$ nc -h 2>&1 | head -1
OpenBSD netcat (Debian patchlevel 1.218-4ubuntu1)
```

**Comment by HenrikBengtsson** [comment]
Dropped use of `nc`. Replaced with `ncat`, if available.  `ss` is the new default, then `netstat`, and `ncat` last.
