### ISSUE TITLE
Python: CLI call should not output error; just return silently with an exit 

### ISSUE THREAD

**Issue by HenrikBengtsson** [HenrikBengtsson/port4me#49]
```sh
$ python3 -m port4me --test=37216; echo $?
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/wynton/home/cbi/hb/.local/lib/python3.11/site-packages/port4me/__main__.py", line 25, in <module>
    if port4me(**args):
       ^^^^^^^^^^^^^^^
  File "/wynton/home/cbi/hb/.local/lib/python3.11/site-packages/port4me/__init__.py", line 167, in port4me
    return is_port_free(test)
           ^^^^^^^^^^^^^^^^^^
  File "/wynton/home/cbi/hb/.local/lib/python3.11/site-packages/port4me/__init__.py", line 33, in is_port_free
    s.bind(("", port))
OSError: [Errno 98] Address already in use
1
$ 
```

The traceback and the error message should not be shown here.

**Comment by HenrikBengtsson** [comment]
* [x] We should also add a test assert this to https://github.com/HenrikBengtsson/port4me/blob/develop/python/tests/port4me.bats.

**Comment by HenrikBengtsson** [comment]
Here's the same in interactive mode:

```python
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> s.bind(("", 0))  ## 0 = ask operating system for a free, random port
>>> addr, port = s.getsockname()
>>> port
41259
>>> port4me(test=port)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henrik/repositories/port4me/python/port4me/__init__.py", line 172, in port4me
    return is_port_free(test)
  File "/home/henrik/repositories/port4me/python/port4me/__init__.py", line 38, in is_port_free
    s.bind(("", port))
OSError: [Errno 98] Address already in use
```

/cc @Finnventor

**Comment by HenrikBengtsson** [comment]
Ah, this was because we only checked for `PermissionError`, but in this case we get an `OSError`, cf. https://github.com/HenrikBengtsson/port4me/commit/b925752c2f919e5e4ad707fcdb0636a54cf456b5
